### ISSUE TITLE
Make the file executable ?

### ISSUE THREAD

**Issue by redcinelli** [elastic/ece-support-diagnostics#117]
I am not sure if this is a good idea, or if it has been done on purpose
But I was with a client today and we had issue figuring out what to do with both `displayCert*` files in the logs we had a `permission denied` error.

I feel maybe we could save time / energy by making all the files executable ?
https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows

If done on purpose ... don't mind me just close the issue

**Comment by jguay** [comment]
I have checked 2.0.7 and both files have execute permission and as far as I can see this was always the case since these 2 files were added in ECE Diag 2.0.0 [here](https://github.com/elastic/ece-support-diagnostics/commit/60f6717a892b5604e3689501b93757599f1677d3#diff-18165afde669ceeb1932d1e8fae45f92367343a1056f556b6bdb327d5109bbc6R22-R25)

[ece-support-diagnostics-v2.0.7-dist.tar.gz](https://github.com/elastic/ece-support-diagnostics/releases/download/v2.0.7/ece-support-diagnostics-v2.0.7-dist.tar.gz) should be unpacked on ECE node with `tar xvf ece-support-diagnostics-v2.0.7-dist.tar.gz` and I've not seen any report of having to run `chmod +x` on those, if you still have the issue, can you confirm the host version and how the distrib file was downloaded and uncompressed
