### ISSUE TITLE
It seems diagnostics.sh doesn't work well with another locale such like 'LC_ALL =ja_JP.UTF-8'

### ISSUE THREAD

**Issue by dharada** [elastic/ece-support-diagnostics#22]
It seems that `diagnostics.sh` depends on `date` command. 

so that if a environment uses another locale setting such like a "ja_JP.UTF-8", it doesn't work well. 

Bad  -> export LC_ALL=ja_JP.UTF-8
Good -> export LC_ALL=en_US.UTF-8

https://stackoverflow.com/questions/12896509/forcing-date-to-use-a-locale-other-than-the-machine-default

could you take a look this issue?

<h4>(log file from a JP customer which includes error)</h4>

[diagnostics.log](https://github.com/elastic/ece-support-diagnostics/files/3459554/diagnostics.log)

**Comment by jguay** [comment]
I don't think we ever tested anything else than OS configured in English American for ECE instances and ECE support diagnostics, I guess the error is `曖昧なリダイレクトです` which translates to `ambiguous redirect` is because our bash script use bad syntax `$var` which is only valid if var has no space characters, strictly speaking we should always use `"$var` to avoid unforeseen behaviour of remove spaces from the variable. I will have a peak at this
