### ISSUE TITLE
Outdated diagnostics.sh (irrelevant for ECE >= 2.5.0)

### ISSUE THREAD

**Issue by mieciu** [elastic/ece-support-diagnostics#61]
The "latest release" pointed by https://github.com/elastic/ece-support-diagnostics#how-to-use is pretty outdated.

Specifically, it's missing [this line](https://github.com/elastic/ece-support-diagnostics/blame/master/diagnostics.sh#L198) which was the fix for https://github.com/elastic/ece-support-diagnostics/issues/49. Without it, when grabbing diagnostics for ECE 2.5.0 and newer all container logs are ignored.

Alternatively we can just make `README.md` point to `master`.

**Comment by jakommo** [comment]
There was a [new release created last week](https://github.com/elastic/ece-support-diagnostics/releases/tag/v1.2) that includes this change.
Are you ok with closing the issue @mieciu ? 

> Alternatively we can just make README.md point to master.

I'm :-1: on this, as it then becomes unclear which version someone is running. 
Rather than doing this, we should speed up our time to release. I already started an internal conversation about this.

**Comment by jguay** [comment]
Closing this as latest release contained the newer code and we currently prefer to keep using release at the moment
